service: platform
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

  environment:
    PLATFORM_TABLE: platform-${sls:stage}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/platform-dev"


functions:
  find-all:
    handler: src/controllers/find-all.handler
    events:
      - httpApi:
          path: /platform
          method: get

  find-by-id:
    handler: src/controllers/find-by-id.handler
    events:
      - httpApi:
          path: /platform/{id}
          method: get

  save:
    handler: src/controllers/save.handler
    events:
      - httpApi:
          path: /platform
          method: post
  
  update:
    handler: src/controllers/update.handler
    events:
      - httpApi:
          path: /platform/{id}
          method: put

  delete:
    handler: src/controllers/delete.handler
    events:
      - httpApi:
          path: /platform/{id}
          method: delete